version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
#     MONGO_INITDB_DATABASE=test
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 142536
    ports:
      - 27017:27017
    volumes:
      - /home/tcl/workspace/data_dump/mongodb/database:/data/db
#       - /home/tcl/workspace/data_dump/mongodb/config:/data/configdb
    restart: unless-stopped

  # mongodb-browser:
  #   image: mongo-express:latest
  #   container_name: mongodb-browser
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_SERVER: 127.0.0.1
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: 142536